### ISSUE TITLE
Reference Documents [EP-FM] and [EP-UC] in the Use Case Analysis document

### ISSUE THREAD

**Issue by MinchellaAndrea** [EOEPCA/use-case-analysis#1]
Hi eoepca team,
in the Use Case Analysis document, there is a reference to two ESA documents ([EP-FM] and [EP-UC]). Would it be possible to get access to both? 

Many thanks 
Andrea

**Comment by rconway** [comment]
The reference documents [EP-UC] and [EP-FM] are now hyperlinked from the main UC document (Issue 0.6, 09/07/2019).
